AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

# Disable metrics for test files - tests can be long
Metrics/ClassLength:
  Exclude:
    - 'test/**/*'
    - 'spec/**/*'


Metrics/BlockLength:
  Exclude:
    - 'test/**/*'
    - 'spec/**/*'
    - '**/*.gemspec'

# Controller module is legitimately large due to comprehensive authorization methods
Metrics/ModuleLength:
  Exclude:
    - 'lib/simple_authorize/controller.rb'

# The policy_class_for method is complex but necessary for flexible policy resolution
# Policy modules have complex conditional logic for various authorization patterns
Metrics/AbcSize:
  Exclude:
    - 'lib/simple_authorize/controller.rb'
    - 'lib/simple_authorize/policy_modules/*.rb'
    - 'test/**/*'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'lib/simple_authorize/controller.rb'
    - 'lib/simple_authorize/policy_modules/*.rb'
    - 'test/**/*'

Metrics/PerceivedComplexity:
  Exclude:
    - 'lib/simple_authorize/controller.rb'
    - 'lib/simple_authorize/policy_modules/*.rb'
    - 'test/**/*'

# Policy module methods need to check multiple conditions
Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'test/**/*'
    - 'spec/**/*'
    - 'lib/simple_authorize/controller.rb'

# OpenStruct is fine for test mocks
Style/OpenStructUse:
  Exclude:
    - 'test/**/*'

# Test classes define policy classes for testing purposes
Lint/ConstantDefinitionInBlock:
  Exclude:
    - 'test/**/*'
    - 'spec/**/*'

# Development dependencies are fine in gemspec
Gemspec/DevelopmentDependencies:
  Enabled: false

# authorize_headless doesn't return boolean, so doesn't need ?
Naming/PredicateMethod:
  Exclude:
    - 'lib/simple_authorize/controller.rb'

# Module documented in main lib/simple_authorize.rb file
# Test files don't need class documentation
Style/Documentation:
  Exclude:
    - 'lib/simple_authorize/configuration.rb'
    - 'test/**/*'
    - 'spec/**/*'
